[project]
name = "communications-helper-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tyler-ingram", email = "tyingram570@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "lmstudio>=1.5.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
communications-helper-agent = "communications_helper_agent:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
